"""add benefits, products, balances

Revision ID: 2061a5688560
Revises: c8a820c46b41
Create Date: 2026-05-02 20:13:42.497032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2061a5688560'
down_revision: Union[str, Sequence[str], None] = 'c8a820c46b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefit_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefit_types_code'), 'benefit_types', ['code'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='productstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_table('product_benefits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('benefit_code', sa.String(length=50), nullable=False),
    sa.Column('annual_limit', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['benefit_code'], ['benefit_types.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_code'], ['products.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code', 'benefit_code', name='uq_product_benefit')
    )
    op.create_index(op.f('ix_product_benefits_benefit_code'), 'product_benefits', ['benefit_code'], unique=False)
    op.create_index(op.f('ix_product_benefits_product_code'), 'product_benefits', ['product_code'], unique=False)
    op.create_table('member_benefit_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_number', sa.String(length=50), nullable=False),
    sa.Column('benefit_code', sa.String(length=50), nullable=False),
    sa.Column('policy_year', sa.Integer(), nullable=False),
    sa.Column('annual_limit', sa.Float(), nullable=False),
    sa.Column('used_amount', sa.Float(), nullable=False),
    sa.Column('remaining_amount', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['benefit_code'], ['benefit_types.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_number'], ['members.member_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_number', 'benefit_code', 'policy_year', name='uq_member_benefit_year')
    )
    op.create_index(op.f('ix_member_benefit_balances_benefit_code'), 'member_benefit_balances', ['benefit_code'], unique=False)
    op.create_index(op.f('ix_member_benefit_balances_member_number'), 'member_benefit_balances', ['member_number'], unique=False)
    op.create_index(op.f('ix_member_benefit_balances_policy_year'), 'member_benefit_balances', ['policy_year'], unique=False)
    # Add as nullable first — existing rows have no value yet
    op.add_column('claim_items', sa.Column('benefit_code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_claim_items_benefit_code'), 'claim_items', ['benefit_code'], unique=False)
    op.create_foreign_key(None, 'claim_items', 'benefit_types', ['benefit_code'], ['code'])

    op.add_column('members', sa.Column('product_code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_members_product_code'), 'members', ['product_code'], unique=False)
    op.create_foreign_key(None, 'members', 'products', ['product_code'], ['code'])

    # Clear stale dev data so we can enforce NOT NULL cleanly after reseeding
    op.execute('TRUNCATE TABLE claim_items CASCADE')
    op.execute('TRUNCATE TABLE claims CASCADE')
    op.execute('TRUNCATE TABLE members CASCADE')

    # Now safe to enforce NOT NULL — tables are empty
    op.alter_column('claim_items', 'benefit_code', nullable=False)
    op.alter_column('members', 'product_code', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_index(op.f('ix_members_product_code'), table_name='members')
    op.drop_column('members', 'product_code')
    op.drop_constraint(None, 'claim_items', type_='foreignkey')
    op.drop_index(op.f('ix_claim_items_benefit_code'), table_name='claim_items')
    op.drop_column('claim_items', 'benefit_code')
    op.drop_index(op.f('ix_member_benefit_balances_policy_year'), table_name='member_benefit_balances')
    op.drop_index(op.f('ix_member_benefit_balances_member_number'), table_name='member_benefit_balances')
    op.drop_index(op.f('ix_member_benefit_balances_benefit_code'), table_name='member_benefit_balances')
    op.drop_table('member_benefit_balances')
    op.drop_index(op.f('ix_product_benefits_product_code'), table_name='product_benefits')
    op.drop_index(op.f('ix_product_benefits_benefit_code'), table_name='product_benefits')
    op.drop_table('product_benefits')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_benefit_types_code'), table_name='benefit_types')
    op.drop_table('benefit_types')
    # ### end Alembic commands ###
