"""add replayed_at to failed_tasks

Revision ID: 288e83a7ac7c
Revises: 9436af8a98d1
Create Date: 2026-05-03 16:38:42.551082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288e83a7ac7c'
down_revision: Union[str, Sequence[str], None] = '9436af8a98d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failed_tasks', sa.Column('replayed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('failed_tasks', 'replayed_at')
    # ### end Alembic commands ###
