"""add failed_tasks table

Revision ID: 9436af8a98d1
Revises: 2061a5688560
Create Date: 2026-05-03 10:52:25.279695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9436af8a98d1'
down_revision: Union[str, Sequence[str], None] = '2061a5688560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failed_tasks')
    # ### end Alembic commands ###
