"""create initial tables

Revision ID: c8a820c46b41
Revises: 
Create Date: 2026-05-02 19:59:27.671481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a820c46b41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_number', sa.String(length=100), nullable=False),
    sa.Column('provider_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VALIDATING', 'ADJUDICATING', 'APPROVED', 'REJECTED', 'FAILED', name='claimstatus'), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('adjudication_result', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_member_number'), 'claims', ['member_number'], unique=False)
    op.create_index(op.f('ix_claims_provider_code'), 'claims', ['provider_code'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='memberstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_member_number'), 'members', ['member_number'], unique=True)
    op.create_index(op.f('ix_members_policy_number'), 'members', ['policy_number'], unique=True)
    op.create_index(op.f('ix_members_status'), 'members', ['status'], unique=False)
    op.create_table('service_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='providerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_providers_provider_code'), 'service_providers', ['provider_code'], unique=True)
    op.create_index(op.f('ix_service_providers_status'), 'service_providers', ['status'], unique=False)
    op.create_table('claim_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_items_claim_id'), 'claim_items', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_items_claim_id'), table_name='claim_items')
    op.drop_table('claim_items')
    op.drop_index(op.f('ix_service_providers_status'), table_name='service_providers')
    op.drop_index(op.f('ix_service_providers_provider_code'), table_name='service_providers')
    op.drop_table('service_providers')
    op.drop_index(op.f('ix_members_status'), table_name='members')
    op.drop_index(op.f('ix_members_policy_number'), table_name='members')
    op.drop_index(op.f('ix_members_member_number'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_provider_code'), table_name='claims')
    op.drop_index(op.f('ix_claims_member_number'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
